openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /public/api/auth/login:
    post:
      tags:
      - public-auth-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              additionalProperties:
                type: string
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                additionalProperties:
                  type: string
  /api/v1/user/details:
    get:
      tags:
      - authenticated-resource-api-controller
      summary: ユーザー情報詳細取得
      description: ユーザー情報詳細を取得する
      operationId: getUserDetails
      parameters:
      - name: emailAddress
        in: query
        required: true
        schema:
          type: string
      - name: versionId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MdmUserDetailResponse'
components:
  schemas:
    MdmUserDetailResponse:
      type: object
      properties:
        userName:
          type: string
        versionId:
          type: string
        lastName:
          type: string
        firstName:
          type: string
        emailAddress:
          type: string
        userNumber:
          type: string
        staticUserId:
          type: string
      description: ユーザー情報詳細のレスポンス
