openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /users:
    get:
      tags:
      - Users
      summary: ユーザー情報一覧
      description: ユーザー情報一覧を取得する
      operationId: getUsers
      parameters:
      - name: id
        in: query
        required: false
        schema:
          type: string
          default: ""
      - name: role
        in: query
        required: false
        schema:
          type: string
          default: ""
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'
        "500":
          description: Internal Server Error
components:
  schemas:
    UserResponse:
      type: object
      properties:
        userId:
          type: string
          description: ユーザーID
          example: MDM00001
        lastName:
          type: string
          description: 姓
          example: Yamada
        firstName:
          type: string
          description: 名
          example: Taro
        role:
          type: string
          description: 役割
          example: OPERATOR
      description: ユーザー情報取得のレスポンス
