openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8080
  description: Generated server url
paths:
  /public/api/auth/register:
    post:
      tags:
      - PublicAuth
      summary: 新規ユーザー登録
      description: 新規ユーザー登録を行うAPIです。
      operationId: register
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRegisterRequest'
        required: true
      responses:
        "200":
          description: 登録成功
          content:
            application/json: {}
  /public/api/auth/login:
    post:
      tags:
      - PublicAuth
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        "200":
          description: ログイン成功
          content:
            application/json: {}
  /api/v1/user/details:
    post:
      tags:
      - authenticated-resource-api-controller
      operationId: getUserDetails
      parameters:
      - name: emailAddress
        in: query
        required: true
        schema:
          type: string
      - name: versionId
        in: query
        required: false
        schema:
          type: integer
          format: int64
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: string
components:
  schemas:
    UserRegisterRequest:
      type: object
      properties:
        first_name:
          type: string
          description: First Name(名)
        last_name:
          type: string
          description: Last Name(姓)
        email_address:
          type: string
          description: E-mailアドレス
        password:
          type: string
          description: パスワード
      description: 新規ユーザー登録のリクエスト
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          description: ユーザー名(Email Address)
        password:
          type: string
          description: パスワード
      description: ログインのリクエスト
