import type { Metadata } from "next";
import "./globals.css";
import { HeroUIProvider } from "@heroui/react";
import Header from "@/components/Header";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <HeroUIProvider>
          <Header />
          <main>
          {children}
          </main>
        </HeroUIProvider>
      </body>
    </html>
  );
}
